services:
  #MySQL
  db:
    image: mysql
    volumes:
      - ./GIFTCARD_SQL:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=GIFTCARDwordpress
      - MYSQL_DATABASE=GIFTCARD
      - MYSQL_USER=GIFTCARDwordpress
      - MYSQL_PASSWORD=GIFTCARDwordpress
  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '5000:80'
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=GIFTCARDwordpress
      - WORDPRESS_DB_PASSWORD=GIFTCARDwordpress
      - WORDPRESS_DB_NAME=GIFTCARD
    volumes:
      - ./wordpress:/var/www/html/wp-content/

volumes:
  dbdata:
networks:
  giftcard: